### ISSUE TITLE
[improvement request] Two modes: "function mode" and "method mode"

### ISSUE THREAD

**Issue by rognoni** [EnzoEghermanne/string-format.js#1]
For my project I was thinking to use your _minimalist_ library instead of this one more complex:

https://github.com/davidchambers/string-format#modes

If you see this link the important missing feature in your library is the ability to choose the **function mode**:
```javascript
format('Hello, {0}!', 'Alice')
```

instead of the **method mode** already implemented:
```javascript
'Hello, {0}!'.format('Alice')
```

@davidchambers uses this strategy:
```javascript
format.extend(String.prototype, {})
```

**Comment by EnzoEghermanne** [comment]
Hello there,

First of all, thanks for showing interest in my _minimalist_ string extension.

Your idea was actually pretty good so I implemented it and it works as follows:

```js
String.format("Hello {0}", "Mrs. Robinson");
```
gives the same output as before: `"Hello Mrs. Robinson"`

There is no need to extend the String object as in the library you referenced,
both "".format(args) and String.format(args) will work.

In the future, you are welcome to submit a pull request for stuff like this :smiley:
